#!/usr/bin/env node
/**
 * fix-names.js — repair ASR name misspellings that plan-vox burned into a book's
 * on-screen text + captions, from a per-book map at books/<slug>/names.json.
 *
 * The VTT is auto-generated by YouTube's ASR, so proper nouns come out garbled
 * ("Vincens", "Orcad", "Kav Akbar", "flight 665"). plan-vox copies that text into
 * beat emphasis/keywords/captions verbatim, so the errors show up big on screen.
 * This rewrites them in place, WITHOUT replanning (timing/images/types untouched).
 *
 * names.json: { "garble": "Correct", ... }  (a leading "_comment" key is ignored)
 *   - matched case-insensitively, on word boundaries
 *   - longest keys applied first (so "Orchidad" wins before "Orchid")
 *   - emphasis / items / kicker are re-UPPERCASED, keywords lowercased
 *
 * Fixes: config.vox.json (props.text/emphasis/keywords/items/kicker/compareLabels,
 * captions[].words[].w) + public/captions/<slug>.clean.vtt + raw <slug>.vtt.
 *
 * Usage: node scripts/fix-names.js --slug=martyr [--dry]
 */
const fs = require("fs");
const path = require("path");
const { abs, rel } = require("./lib/paths");

const ROOT = path.join(__dirname, "..");
const args = Object.fromEntries(
  process.argv.slice(2).map((a) => {
    const m = a.match(/^--([^=]+)=(.*)$/);
    return m ? [m[1], m[2]] : [a.replace(/^--/, ""), true];
  }),
);
const SLUG = args.slug;
if (!SLUG) { console.error("Kullanım: node scripts/fix-names.js --slug=<slug> [--dry]"); process.exit(1); }

const mapPath = path.join(ROOT, "books", SLUG, "names.json");
if (!fs.existsSync(mapPath)) { console.error(`❌ ${rel.book ? rel.book(SLUG) : "books/" + SLUG}/names.json yok.`); process.exit(1); }
const rawMap = JSON.parse(fs.readFileSync(mapPath, "utf8"));
const pairs = Object.entries(rawMap)
  .filter(([k]) => k !== "_comment")
  .sort((a, b) => b[0].length - a[0].length); // longest first

const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
// word-ish boundary that also works when the token is wrapped by the JSON/VTT
const rxFor = (k) => new RegExp(`(^|[^A-Za-z0-9])(${esc(k)})(?=[^A-Za-z0-9]|$)`, "gi");

let hits = 0;
const applyStr = (s) => {
  if (typeof s !== "string" || !s) return s;
  let out = s;
  for (const [k, v] of pairs) out = out.replace(rxFor(k), (m, pre) => { hits++; return pre + v; });
  return out;
};

// ── config.vox.json ─────────────────────────────────────────────────────────
const cfgAbs = abs.voxConfig(SLUG);
if (!fs.existsSync(cfgAbs)) { console.error(`❌ ${rel.voxConfig(SLUG)} yok.`); process.exit(1); }
const cfg = JSON.parse(fs.readFileSync(cfgAbs, "utf8"));
let beatHits = 0;
for (const b of cfg.beats) {
  const p = b.props; if (!p) continue;
  const before = JSON.stringify(p);
  if (p.text) p.text = applyStr(p.text);
  // Arrays: join → apply (so multi-word garbles split across elements, e.g.
  // ["CYBER","SHIMS"], still match "Cyber Shims") → re-split, drop empties.
  const fixArr = (a, cas) => applyStr(a.join(" ")).split(/\s+/).filter(Boolean).map((w) => cas(w));
  const UP = (w) => w.toUpperCase(), LO = (w) => w.toLowerCase();
  if (Array.isArray(p.emphasis)) p.emphasis = fixArr(p.emphasis, UP).slice(0, 3);
  if (Array.isArray(p.items)) p.items = fixArr(p.items, UP);
  if (Array.isArray(p.keywords)) p.keywords = p.keywords.map((e) => applyStr(String(e)).toLowerCase());
  if (Array.isArray(p.compareLabels)) p.compareLabels = fixArr(p.compareLabels, UP);
  if (p.kicker) p.kicker = applyStr(p.kicker).toUpperCase();
  if (p.title) p.title = applyStr(p.title);
  if (JSON.stringify(p) !== before) beatHits++;
}
let capWords = 0;
for (const c of cfg.captions || []) {
  if (Array.isArray(c.words)) for (const w of c.words) { const b = w.w; w.w = applyStr(w.w); if (w.w !== b) capWords++; }
  if (typeof c.text === "string") c.text = applyStr(c.text);
}

// ── clean.vtt + raw vtt ─────────────────────────────────────────────────────
const vtts = [
  path.join(ROOT, "public", "captions", `${SLUG}.clean.vtt`),
  path.join(ROOT, "public", "captions", `${SLUG}.vtt`),
];
const vttResults = [];
for (const v of vtts) {
  if (!fs.existsSync(v)) continue;
  const src = fs.readFileSync(v, "utf8");
  const before = hits;
  const out = applyStr(src);
  vttResults.push({ v, changed: hits - before, out, src });
}

console.log(`\n══ İSİM DÜZELT → ${SLUG}  (${pairs.length} kural)`);
console.log(`   config beat değişen: ${beatHits} · caption kelime: ${capWords}`);
vttResults.forEach((r) => console.log(`   ${path.relative(ROOT, r.v)}: ${r.changed} düzeltme`));
console.log(`   toplam eşleşme: ${hits}`);

if (args.dry) { console.log("\n(--dry: dosya yazılmadı)"); process.exit(0); }
if (!hits) { console.log("\n✓ Değişiklik yok."); process.exit(0); }
fs.copyFileSync(cfgAbs, cfgAbs + ".bak");
fs.writeFileSync(cfgAbs, JSON.stringify(cfg, null, 2));
vttResults.forEach((r) => { if (r.out !== r.src) fs.writeFileSync(r.v, r.out); });
console.log(`\n✓ ${rel.voxConfig(SLUG)} + altyazılar güncellendi (config yedeği: .bak)`);
