// AUTO-GENERATED by scripts/gen-books-registry.js — do not edit by hand.
// Regenerate with: node scripts/gen-books-registry.js

import ant_crime_and_punishment from '../books/crime-and-punishment/config.antidote.json';
import ant_meta_crime_and_punishment from '../books/crime-and-punishment/youtube-meta.json';
import ant_the_myth_of_sisyphus from '../books/the-myth-of-sisyphus/config.antidote.json';
import ant_meta_the_myth_of_sisyphus from '../books/the-myth-of-sisyphus/youtube-meta.json';
import ant_the_republic from '../books/the-republic/config.antidote.json';
import ant_meta_the_republic from '../books/the-republic/youtube-meta.json';

export type Palette = { paper: string; ink: string; red: string; gold: string; captionHighlight?: string };

export type BookEntry = {
  slug: string;
  engine: 'vox' | 'antidote';
  config: any;
  meta: any | null;
};

export type AntidoteBookEntry = {
  slug: string;
  engine: 'vox' | 'antidote';
  config: any;
  meta?: any | null;
};

// Per-book palettes (from books/<slug>/book.json). resolvePalette() in voxkit and
// the Antidote thumbnail read this so each book has its own color identity.
export const BOOK_PALETTES: Record<string, Palette> = {
  'crime-and-punishment': { paper: '#F5F2EB', ink: '#181716', red: '#991B1B', gold: '#C28E38' },
  'the-myth-of-sisyphus': { paper: '#FBF9F5', ink: '#1C1917', red: '#DC2626', gold: '#D97706' },
  'the-republic': { paper: '#F6F1E8', ink: '#181514', red: '#B83A24', gold: '#C98A2C' },
};

// Books opted into the palette-tinted background (new books; see book.json.bgTint).
export const BOOK_BG_TINT: Record<string, boolean> = {
  'crime-and-punishment': true,
  'the-myth-of-sisyphus': true,
  'the-republic': true,
};

export const BOOKS: BookEntry[] = [

];

export const ANTIDOTE_BOOKS: AntidoteBookEntry[] = [
  {
    slug: 'crime-and-punishment',
    engine: 'antidote',
    config: ant_crime_and_punishment as any,
    meta: ant_meta_crime_and_punishment as any,
  },
  {
    slug: 'the-myth-of-sisyphus',
    engine: 'antidote',
    config: ant_the_myth_of_sisyphus as any,
    meta: ant_meta_the_myth_of_sisyphus as any,
  },
  {
    slug: 'the-republic',
    engine: 'antidote',
    config: ant_the_republic as any,
    meta: ant_meta_the_republic as any,
  },
];
